package common;

public enum PageType {
	HOME_PAGE, 
	LIST_PAGE,
	CATEGORY_PAGE, 
	FAVORITES_PAGE,
	VIDEO_MANAGER_PAGE,
	VIDEO_CATEGORY_MANAGER_PAGE,
	USER_MANAGER_PAGE,
	VIDEO_DETAIL_PAGE,
	FOUND_VIDEO_PAGE,
	WATCH_VIDEO_PAGE
}
